#!/bin/bash

awk -v hide=1 '
	/chapter/ {print} 
	/end{Exercice}/ {print "\\refstepcounter{Exercice}\n"} 
	/begin{Solution}/ {hide=0} 
	/end{Solution}/ {hide=1;print $0 "\n"} 
	hide==0 {print}
	' syllabus/tableau2D.tex syllabus/oo.tex syllabus/liste.tex syllabus/rupture.tex syllabus/donnee.tex > solutionbook/solutions.tex
